### ISSUE TITLE
Use specific DevEui, AppEui, AppKey, NewSKey, AppSKey, DevAddr Types in Encoding

### ISSUE THREAD

**Issue by lthiery** [lora-rs/lora-rs#134]
It's currently inconsistent in its use of AES128 type:
```rust
pub enum JoinMode {
    OTAA { deveui: [u8; 8], appeui: [u8; 8], appkey: [u8; 16] },
    ABP { newskey: AES128, appskey: AES128, devaddr: DevAddr<[u8; 4]> },
}
```

It's generally preferable to have specialized types, so OTAA should adopt AES128 as well. 

We probably want to make special types for DevEui and AppEui as well?

**Comment by ivajloip** [comment]
Is [EUI64](https://github.com/ivajloip/rust-lorawan/blob/master/encoding/src/parser.rs#L912) something that will help here? Otherwise, sure, we can have separate types for those.

**Comment by lthiery** [comment]
Yes, I do think EUI64 is appropriate for AppEui & DevEui. But we still might want to use a new type tho and do something like `struct AppEui(EUI64)`.

**Comment by ivajloip** [comment]
sounds good! 🙂

**Comment by lthiery** [comment]
#137 updates the device types to be more specific. It would still be good to update the encoding API to use these specific types as well. Work is being deferred for now as it should be paired with other breaking changes in the encoding library.

**Comment by lthiery** [comment]
@ivajloip let me know how #177 looks to you
