### ISSUE TITLE
Drop bundled trallocator in favor of existing crate?

### ISSUE THREAD

**Issue by plaes** [lora-rs/lora-rs#163]
Based on git history, I can assume that trallocator was bundled due to lack of published crate? Now that there is one, could we drop the bundled code in favor of this crate?
* https://crates.io/crates/trallocator
* https://github.com/xgroleau/trallocator

cc: @ivajloip 

[edit]: Current trallocator code probably originates from this thread from reddit: https://www.reddit.com/r/rust/comments/8z83wc/is_there_any_way_to_benchmark_memory_usage_in_rust/

**Comment by ivajloip** [comment]
I would be in favor of dropping the current implementation - let me know if you would have the chance to create a PR for that, otherwise I will take a look at it when I have a moment (probably next week).
